### ISSUE TITLE
Test Pegasus Frontend

### ISSUE THREAD

**Issue by tcamargo** [tcamargo/batocera.linux#3]
http://pegasus-frontend.org/
To do:
* ...

**Comment by tcamargo** [comment]
http://doc.qt.io/qt-5/embedded-linux.html

For sqllite support: BR2_PACKAGE_QT5BASE_SQLITE_SYSTEM - solved

For keyboard to work:  QT_QPA_EGLFS_NO_LIBINPUT=1 -- only if using eglfs

Workaround for nvidia - BR2_PACKAGE_QT5BASE_XCB

**Comment by tcamargo** [comment]
[w] qrc:/frontend/menu/settings/GamepadEditor.qml:22:1: module "QtGamepad" is not installed
**solved**
https://github.com/batocera-linux/batocera.linux/commit/54f36de1c3b0b8d30aafdd5da5d4b88c75b294ca
and previous 2 commits.

**Comment by tcamargo** [comment]
video problem. arcade video snaps don't work. -- **solved**
[w] Error: "Internal data stream error."
        select BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_AUDIOCONVERT # runtime
      	select BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_AUDIOMIXER # runtime
      	select BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_AUDIORESAMPLE # runtime
      	select BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_VIDEOCONVERT # runtime
      	select BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_VIDEOSCALE # runtime
      	select BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_VOLUME # runtime
      	select BR2_PACKAGE_GST1_PLUGINS_GOOD_PLUGIN_IMAGEFREEZE # runtime

**Comment by mmatyas** [comment]
Hi, "Internal data stream error" comes from GStreamer, and can be caused by various reasons like bugs in a GStreamer codec, hardware issues, unsupported media format, etc. Do you see any "Additional debug info" on the terminal/log, like [here](https://github.com/thaytan/gst-rpicamsrc/issues/76)? Perhaps a similar debugging with `gst-launch` could also help, it has more documentation [here](https://gstreamer.freedesktop.org/documentation/tutorials/basic/gstreamer-tools.html).

**Comment by tcamargo** [comment]
moved to https://batocera-linux.xorhub.com/todo/index.php?do=details&task_id=65
